# Starter pipelineAdd commentMore actions
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - qa

variables:
  - group: BuildVariables
  - name: buildConfiguration
    value: 'Debug'
  - name: outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/output'

jobs:
- job: Build_Main
  displayName: 'Build Main'
  pool:
   vmImage: 'macos-15'
   demands: xcode

  steps:
   
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - task: CmdLine@2
    displayName: "dotnet workload restore"
    inputs:
      script: 'dotnet workload restore'
  
  - task: CmdLine@2
    displayName: "Select a specific version of Xcode"
    inputs:
      script: 'sudo xcode-select -s /Applications/Xcode_16.3.app'


  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'AppleDeveloperCertificate.p12'
      certPwd: '$(iOSCertPassword)'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: 'VS_comlinkedinlearningqrtracker_Development.mobileprovision'

  - task: DotNetCoreCLI@2
    displayName: 'Build project for iOS'
    inputs:
     command: build
     projects: 'QRTracker/QrTracker.csproj'
     arguments: '-f net9.0-ios --configuration $(buildConfiguration) --output $(outputDirectory)/ios'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build project for MacOS'
    inputs:
     command: build
     projects: 'QRTracker/QrTracker.csproj'
     arguments: '-f net9.0-maccatalyst --configuration $(buildConfiguration) --output $(outputDirectory)/MacOS'