# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   exclude:
     - '*'

pr:
  branches:
    include:
      - main

variables:
  - name: buildConfiguration
    value: 'Debug'
  - name: outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/output'

jobs:
- job: Build_Main
  displayName: 'Build Main'
  pool:
   vmImage: 'macos-latest'
   demands: xcode

  steps:
   
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - task: CmdLine@2
    displayName: "dotnet workload restore"
    inputs:
      script: 'dotnet workload restore'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build project for Android'
    inputs:
     command: build
     projects: 'QRTracker/QrTracker.csproj'
     arguments: '-f net9.0-android --configuration $(buildConfiguration) --output $(outputDirectory)/Android'